### ISSUE TITLE
Repository doesn't include a src or examples folder

### ISSUE THREAD

**Issue by mikeshatch** [Exeton/EasyEnchants#4]
Consider adding a src and examples folder.

**Comment by Exeton** [comment]
Sorry for the bad response time. There should be a src folder inside at /easy_enchants/. I still need to add an examples fold though. I think moving the sample enchants into an example folder will make it a lot easier for other people to learn how to use the API.

**Comment by mikeshatch** [comment]
> Sorry for the bad response time. 

No worries. I opened this after watching Eddie & Andrew's video where they mentioned src/examples. It was Issues practice for me. I was under the impression that there should be a src folder in the main area, but good to know. Thank you.
